package Presentacion;

import java.awt.GridLayout;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import cliente.GestorCliente;

/**
 *
 * @author Usuario
 */
public class PrincipalApp extends javax.swing.JFrame {
	private GestorCliente gc;
	private String user;
    /**
     * Creates new form PrincipalApp
     */
    public PrincipalApp(GestorCliente g, String u) {
    	this.gc = g;
    	this.user = u;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 537));
        getContentPane().setLayout(null);
        jLabel1.setBounds(0, 0, 630, 490);
/*
        File famigos = new File("usuarios/" + user + ".txt");
    	
    	DataInputStream disAmigos;
		try {
			disAmigos = new DataInputStream(new FileInputStream(famigos));
			String linea = disAmigos.readLine();
	    	linea = disAmigos.readLine();
	    	while(linea != null) {
	    		File carpetaFotos = new File("src/imagenes/usuarios" + linea);
	    		JLabel[] etiquetasFotos = new JLabel[carpetaFotos.list().length];
	    		String nombre = "foto";
	    		int i = 0;
	    		for(File f : carpetaFotos.listFiles()) {
	    			String path = f.getAbsolutePath();
	    			URL url = this.getClass().getResource(path);
	    			ImageIcon icon = new ImageIcon(url);
	    			etiquetasFotos[i] = new JLabel();
	    			etiquetasFotos[i].setIcon(icon);
	    			jScrollPane1.add(etiquetasFotos[i]);
	    			i++;
	    		}
	    		linea = disAmigos.readLine();
	    	}
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	//Linea contraseña
 catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	JFrame ventana = new JFrame();
    	JPanel panel = new JPanel();
    	
    	panel.setLayout(new GridLayout(gc.mostrarFotos(user).size(), 1));
    	for(ImageIcon i : gc.mostrarFotos(user)) {
    		JLabel imagen = new JLabel();
    		imagen.setIcon(i);
    		panel.add(imagen);
    	}
        btSubir = new javax.swing.JButton();
        btRecargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane(panel);
        btEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btSeguirAmigo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btSubir.setText("Subir Foto");
        btSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubirActionPerformed(evt);
            }
        });
        getContentPane().add(btSubir);
        btSubir.setBounds(260, 440, 110, 25);

        btRecargar.setText("Recargar");
        btRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecargarActionPerformed(evt);
            }
        });
        getContentPane().add(btRecargar);
        btRecargar.setBounds(470, 440, 110, 25);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 570, 360);
        
    	
    	
    

        btEliminar.setText("Eliminar foto");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btEliminar);
        btEliminar.setBounds(50, 440, 110, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("ASPIC");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 10, 100, 40);

        btSeguirAmigo.setText("Seguir usuario");
        btSeguirAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeguirAmigoActionPerformed(evt);
            }
        });
        getContentPane().add(btSeguirAmigo);
        btSeguirAmigo.setBounds(470, 20, 120, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aplicacion/fondo-degradado.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(2, 0, 630, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubirActionPerformed
        // TODO add your handling code here:
    	JFileChooser jfc = new JFileChooser();
    	if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
    		System.out.println("ENTRA IF");
    		gc.subirFoto(jfc.getSelectedFile(), this.user);
    	}
    	
    	System.out.println("btSubir");
    }//GEN-LAST:event_btSubirActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
    	
    	gc.eliminarFoto("hola_FECHA.jpg", user);
    	System.out.println("btEliminar");
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecargarActionPerformed
        List<ImageIcon> imagenes= gc.mostrarFotos(user);
        JFrame ventana = new JFrame();
    	JPanel panel = new JPanel();
        for(ImageIcon imagen : imagenes) {
        	//JFrame ventana = new JFrame("Imagen");
        	JLabel etiqueta = new JLabel();
        	
        	etiqueta.setIcon(imagen);
        	jScrollPane1.setViewportView(etiqueta);
        }
    	
    	
    	
    }//GEN-LAST:event_btRecargarActionPerformed

    private void btSeguirAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeguirAmigoActionPerformed
        // TODO add your handling code here:
        SeguirAmigo seguir = new SeguirAmigo(this.gc, this.user);
        seguir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btSeguirAmigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btRecargar;
    private javax.swing.JButton btSeguirAmigo;
    private javax.swing.JButton btSubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
