/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import cliente.GestorCliente;

/**
 *
 * @author Usuario
 */
public class Registro extends javax.swing.JFrame {
	private GestorCliente gc = null;
    /**
     * Creates new form Registro
     */
    public Registro(GestorCliente g) {
    	this.gc = g;
        initComponents();
        this.setExtendedState(this.jLabel1.getWidth());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JTextField();
        tfRepiteContraseña = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btRegistrarse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 537));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Aspic");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, -30, 160, 150);

        tfUsuario.setName("tfnombreusuario"); // NOI18N
        getContentPane().add(tfUsuario);
        tfUsuario.setBounds(290, 100, 130, 30);
        getContentPane().add(tfContraseña);
        tfContraseña.setBounds(290, 150, 130, 30);
        getContentPane().add(tfRepiteContraseña);
        tfRepiteContraseña.setBounds(290, 200, 130, 30);
        getContentPane().add(tfEmail);
        tfEmail.setBounds(290, 250, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Nombre de usuario:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 90, 180, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("ContraseÃ±a:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 150, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Repetir contraseÃ±a:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 200, 190, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 250, 180, 22);

        taDescripcion.setColumns(20);
        taDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taDescripcion.setRows(5);
        jScrollPane1.setViewportView(taDescripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 300, 310, 100);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Registro");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 10, 160, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Breve descripciÃ³n:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 310, 190, 22);

        btRegistrarse.setText("Registrarme");
        btRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrarse);
        btRegistrarse.setBounds(290, 430, 140, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aplicacion/fondo-degradado.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarseActionPerformed
        // TODO add your handling code here:
    	if(gc.registrarse(this.tfUsuario.getText(), this.tfContraseña.getText())) {
    		Login l = new Login();
    		l.setVisible(true);
    		this.dispose();
    	}
    }//GEN-LAST:event_btRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfRepiteContraseña;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
